### Get request to fetch all users
GET http://localhost:3000/users

###

### Get request to fetch a specific user
GET http://localhost:3000/users/67910295058fc158b61a54ae

###

### POST request to create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "Marcel",
    "lastname": "Max",
    "email": "marcelsam@mail.com",
    "favcolor": "Pink",
    "birthdate": "09/26/1995"
}

###

### PUT request to update a user
PUT http://localhost:3000/users/6791105ce841fbc40d14591c
Content-Type: application/json

{
    "firstname": "Marceia",
    "lastname": "Maxima",
    "email": "marcelsam@mail.com",
    "favcolor": "Pink",
    "birthdate": "09/26/1995"
}

###

DELETE http://localhost:3000/users/67910f9ce841fbc40d14591b